"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h5)!h#(bd5*fp%qx=91q_05k#@0&f#hx3syq*v3$j_3x^d77f5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# 2. Trusted Origins (Port 8000'i mutlaka açıkça belirtmelisin)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://ekomaxi.localhost:8000',   # wildcard yerine explicit yaz
    'http://*.localhost:8000',
    "http://*.localhost:5173", 
]

# 3. Ek Güvenlik Ayarları (Geliştirme aşamasında bunları esnetelim)
CSRF_COOKIE_HTTPONLY = False  # Javascript'in cookie'yi görmesine izin ver (Hata ayıklama için)
SESSION_COOKIE_SECURE = False # HTTP (S'siz) kullandığımız için False olmalı
CSRF_COOKIE_SECURE = False    # HTTP kullandığımız için False olmalı

SESSION_COOKIE_DOMAIN = '.localhost'   # tüm subdomainler için
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False          # production'da True yaparsın
SESSION_COOKIE_NAME = 'sessionid'

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-slug',   # bunu ekle
]

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CORS_ALLOW_CREDENTIALS = True

SHARED_APPS = [
    'django_tenants',  # Mutlaka en üstte olmalı
    'customers', # Tenant modelini burada tanımlayacağız
    'corsheaders',
    'management',      # Ortak uygulamalar burada olabilir
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    "django.contrib.staticfiles"
]

# Tenants için özel ayarlar
TENANT_APPS = [
    'django.contrib.auth', # Firmaların kendi kullanıcıları olabilir
    'django.contrib.contenttypes',
    
    # Kendi uygulamaların buraya gelecek
    'management', 
]

# Tenant modelini belirtiyoruz
TENANT_MODEL = 'customers.Client'
TENANT_DOMAIN_MODEL = 'customers.Domain'


DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
# Application definition
INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware', # Her zaman 1. sırada
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Session önce
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',           # CSRF sonra
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localhost:5173$",
    r"^http://localhost:5173$",
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django_tenants.postgresql_backend',  # Genellikle doğru ama hata alıyorsan aşağıya bak
        'NAME': 'senkroon',
        'USER': 'senkroon',
        'PASSWORD': 'senkroon789654.',
        'HOST': 'localhost',
        'PORT': '5432', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Geliştirme aşamasında şuna da ihtiyaç olabilir:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# settings.py
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}