# Generated by Django 6.0.3 on 2026-03-17 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteAna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_Guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('en', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='En (m)')),
                ('boy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Boy (m)')),
                ('yukseklik', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yükseklik (m)')),
                ('malzeme', models.CharField(choices=[('AISI304', 'Paslanmaz AISI 304'), ('AISI316', 'Paslanmaz AISI 316'), ('SDG', 'Sıcak Daldırma Galvaniz'), ('PREGALVANIZ', 'Pre-Galvaniz')], default='AISI304', max_length=50)),
                ('standart', models.CharField(choices=[('EKOMAXI', 'Ekomaxi Standart'), ('CEVRE_SEHIRCILIK', 'Çevre Şehircilik Standartı')], default='EKOMAXI', max_length=50)),
                ('taban_tipi', models.CharField(choices=[('DUZ', 'Düz Taban'), ('BOMBELI', 'Bombeli Taban')], default='DUZ', max_length=50)),
                ('olusturan_user', models.CharField(blank=True, max_length=100, null=True)),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reçete Ana (Depo Yapılandırması)',
                'verbose_name_plural': '2. Reçete Başlıkları',
            },
        ),
        migrations.CreateModel(
            name='StokKarti',
            fields=[
                ('sto_Guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sto_kod', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Stok Kodu')),
                ('sto_isim', models.CharField(max_length=255, verbose_name='Stok Adı')),
                ('sto_birim1_ad', models.CharField(default='Adet', max_length=20)),
                ('bom_kategori', models.CharField(blank=True, db_index=True, help_text='Duvar Paneli, Taban Sacı, Civata, Conta vb.', max_length=100, null=True)),
                ('bom_malzeme', models.CharField(blank=True, choices=[('AISI304', 'Paslanmaz AISI 304'), ('AISI316', 'Paslanmaz AISI 316'), ('SDG', 'Sıcak Daldırma Galvaniz'), ('PREGALVANIZ', 'Pre-Galvaniz')], max_length=50, null=True)),
                ('bom_kalinlik_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bom_ebat', models.CharField(blank=True, help_text='Örn: 1x1, 0.5x1, 1x2', max_length=50, null=True)),
                ('sto_muh_kod', models.CharField(default='153', max_length=50)),
                ('sto_pasif_fl', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Stok Kartı',
                'verbose_name_plural': '1. Stok Kartları',
            },
        ),
        migrations.CreateModel(
            name='ReceteSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_satirno', models.IntegerField(verbose_name='Satır No')),
                ('rec_tuketim_miktar', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miktar')),
                ('rec_tuketim_birim', models.CharField(default='Adet', max_length=20)),
                ('not_alani', models.CharField(blank=True, help_text='Örn: 1. Kat Duvar Paneli', max_length=255, null=True)),
                ('aktarildi_mi', models.BooleanField(default=False, verbose_name="Mikro'ya Aktarıldı")),
                ('recete_ana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='bom_engine.receteana')),
                ('rec_tuketim_kod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom_engine.stokkarti', verbose_name='Kullanılan Parça')),
            ],
            options={
                'verbose_name': 'Reçete Satırı (BOM Line)',
                'verbose_name_plural': '3. Reçete Detay Satırları',
                'ordering': ['rec_satirno'],
            },
        ),
        migrations.AddField(
            model_name='receteana',
            name='rec_anakod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom_engine.stokkarti', verbose_name='Ana Mamul'),
        ),
    ]
