# Generated by Django 6.0.3 on 2026-03-18 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Standart Kategorisi',
                'verbose_name_plural': 'Standart Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('stock_guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stock_code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Stock Code')),
                ('stock_name', models.CharField(max_length=255, verbose_name='Stock Name')),
                ('unit_name', models.CharField(default='Piece', max_length=20, verbose_name='Unit Name')),
                ('bom_category', models.CharField(blank=True, db_index=True, help_text='Wall Panel, Base Sheet, Bolt, Gasket, etc.', max_length=100, null=True, verbose_name='BOM Category')),
                ('bom_material', models.CharField(blank=True, choices=[('AISI304', 'Paslanmaz AISI 304'), ('AISI316', 'Paslanmaz AISI 316'), ('SDG', 'Sıcak Daldırma Galvaniz'), ('PREGALVANIZ', 'Pre-Galvaniz')], max_length=50, null=True, verbose_name='BOM Material')),
                ('bom_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BOM Thickness (mm)')),
                ('bom_dimensions', models.CharField(blank=True, help_text='E.g.: 1x1, 0.5x1, 1x2', max_length=50, null=True, verbose_name='BOM Dimensions')),
                ('accounting_code', models.CharField(default='153', max_length=50, verbose_name='Accounting Code')),
                ('is_passive', models.BooleanField(default=False, verbose_name='Is Passive?')),
            ],
            options={
                'verbose_name': 'Stock Card',
                'verbose_name_plural': '1. Stock Cards',
            },
        ),
        migrations.RemoveField(
            model_name='recetesatir',
            name='recete_ana',
        ),
        migrations.RemoveField(
            model_name='recetesatir',
            name='rec_tuketim_kod',
        ),
        migrations.CreateModel(
            name='ReferenceBomHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(help_text='e.g., Pre Galvanized-SDG, 304 Stainless', max_length=100)),
                ('min_tonnage', models.IntegerField(default=0, verbose_name='Minimum Tonnage')),
                ('max_tonnage', models.IntegerField(verbose_name='Maximum Tonnage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_boms', to='bom_engine.standardcategory')),
            ],
            options={
                'verbose_name': '2. Reference BOM Header',
                'verbose_name_plural': '2. Reference BOM Headers',
                'unique_together': {('category', 'material_type', 'min_tonnage', 'max_tonnage')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_module_height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Total Tank Height')),
                ('zone_type', models.CharField(choices=[('WALL', 'Side Wall Panel'), ('BASE', 'Base Panel'), ('ROOF', 'Roof Panel'), ('COVER', 'Manhole / Cleaning Cover')], max_length=20)),
                ('layer_level', models.DecimalField(blank=True, decimal_places=1, help_text='Layer number from bottom to top (Applicable for WALLs)', max_digits=4, null=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom_engine.referencebomheader')),
                ('stock_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom_engine.stockcard', verbose_name='Selected Stock')),
            ],
            options={
                'verbose_name': '3. Reference BOM Line',
                'verbose_name_plural': '3. Reference BOM Lines',
                'ordering': ['total_module_height', 'zone_type', 'layer_level'],
            },
        ),
        migrations.DeleteModel(
            name='ReceteAna',
        ),
        migrations.DeleteModel(
            name='ReceteSatir',
        ),
        migrations.DeleteModel(
            name='StokKarti',
        ),
    ]
