# Generated by Django 6.0.3 on 2026-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0002_standardcategory_stockcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcard',
            name='accounting_code',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='bom_category',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='bom_dimensions',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='bom_material',
        ),
        migrations.AddField(
            model_name='stockcard',
            name='bom_category_code1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM Category Code 1'),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='bom_category_code2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM Category Code 2'),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='bom_category_code3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM Category Code 3'),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='bom_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BOM Length (mm)'),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='bom_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BOM Width (mm)'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='is_passive',
            field=models.BooleanField(default=True, verbose_name='Is Passive?'),
        ),
    ]
