# Generated by Django 6.0.3 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0003_remove_stockcard_accounting_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='bom_category_code4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM Category Code 3'),
        ),
    ]
