# Generated by Django 6.0.3 on 2026-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0004_stockcard_bom_category_code4'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='stock_code_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock Code 1'),
        ),
    ]
