# Generated by Django 6.0.3 on 2026-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0005_stockcard_stock_code_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='bom_category_code4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM Category Code 4'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='bom_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='BOM Length (mm)'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='bom_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='BOM Thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='bom_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='BOM Width (mm)'),
        ),
    ]
