# Generated by Django 6.0.3 on 2026-03-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0006_alter_stockcard_bom_category_code4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencebomline',
            options={'ordering': ['total_module_height', 'zone_type', 'layer_level'], 'verbose_name': '5. Reference BOM Line', 'verbose_name_plural': '5. Reference BOM Lines'},
        ),
        migrations.AddField(
            model_name='referencebomline',
            name='required_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gereken Kalınlık (Paneller İçin)'),
        ),
        migrations.AlterField(
            model_name='referencebomline',
            name='layer_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='referencebomline',
            name='stock_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bom_engine.stockcard', verbose_name='Doğrudan Stok Seçimi (Aksesuarlar İçin)'),
        ),
        migrations.AlterField(
            model_name='referencebomline',
            name='zone_type',
            field=models.CharField(choices=[('WALL', 'Side Wall Panel'), ('BASE', 'Base Panel'), ('ROOF', 'Roof Panel'), ('COVER', 'Manhole / Cleaning Cover'), ('ACCESSORY', 'Aksesuarlar (Merdiven vb.)')], max_length=20),
        ),
        migrations.CreateModel(
            name='VariantMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('AISI304', 'Paslanmaz AISI 304'), ('AISI316', 'Paslanmaz AISI 316'), ('SDG', 'Sıcak Daldırma Galvaniz'), ('PREGALVANIZ', 'Pre-Galvaniz')], db_index=True, max_length=100, verbose_name='Malzeme Tipi')),
                ('description', models.CharField(blank=True, help_text='Örn: Yarım Panel 0.54x1.08', max_length=255, null=True, verbose_name='Açıklama / Ebat (Kritik!)')),
                ('produced_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bom_engine.stockcard', verbose_name='Üretilecek Nihai Stok')),
            ],
            options={
                'verbose_name': '2. Variant Mapping',
                'verbose_name_plural': '2. Variant Mappings',
            },
        ),
    ]
