# Generated by Django 6.0.3 on 2026-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0007_alter_referencebomline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
