# Generated by Django 6.0.3 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_engine', '0008_stockcard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebomline',
            name='zone_type',
            field=models.CharField(choices=[('WALL', 'Side Wall Panel'), ('BASE', 'Base Panel'), ('ROOF', 'Roof Panel'), ('COVER', 'Manhole / Cleaning Cover'), ('ACCESSORY', 'Aksesuarlar (Merdiven vb.)'), ('EXTERNAL_ANGLE', 'Dış Köşebent / Destek'), ('INTERNAL_TIE', 'İç Gergi (Tij)')], max_length=20),
        ),
    ]
